[2024-10-13T19:36:16.724+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:36:00.624470+00:00 [queued]>
[2024-10-13T19:36:16.728+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:36:00.624470+00:00 [queued]>
[2024-10-13T19:36:16.728+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:36:16.728+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-13T19:36:16.728+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:36:16.733+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): S3_to_DB> on 2024-10-13 19:36:00.624470+00:00
[2024-10-13T19:36:16.737+0000] {standard_task_runner.py:55} INFO - Started process 1247 to run task
[2024-10-13T19:36:16.739+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Demo', 'S3_to_DB', 'manual__2024-10-13T19:36:00.624470+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Demo.py', '--cfg-path', '/tmp/tmp11ayx2zf']
[2024-10-13T19:36:16.740+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask S3_to_DB
[2024-10-13T19:36:16.756+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T19:36:16.781+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:36:00.624470+00:00 [running]> on host c3a571b96d5f
[2024-10-13T19:36:16.808+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Demo
AIRFLOW_CTX_TASK_ID=S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T19:36:00.624470+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T19:36:00.624470+00:00
[2024-10-13T19:36:16.809+0000] {s3_db.py:129} INFO - Executing S3 File read.......
[2024-10-13T19:36:16.809+0000] {s3_db.py:16} INFO - Creating Spark session ......
[2024-10-13T19:36:19.284+0000] {s3_db.py:71} INFO - Executing File pattern check......
[2024-10-13T19:36:19.284+0000] {logging_mixin.py:137} INFO - prefix: sftp_file_receiver
[2024-10-13T19:36:19.635+0000] {s3_db.py:116} INFO - Latest file for pattern - sftp_s3_\d{8}\.csv at s3a://sdevalla-buck/sftp_file_receiver: sftp_s3_20241013.csv
[2024-10-13T19:36:22.932+0000] {s3_db.py:51} INFO - Updating run log for read operation....
[2024-10-13T19:36:22.935+0000] {s3_db.py:55} INFO - Run log updated successfully....
[2024-10-13T19:36:22.939+0000] {s3_db.py:238} INFO - Executing file writing function .....
[2024-10-13T19:36:23.256+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/s3_db.py", line 310, in main_s3_db
    result = db_file_write(db_conn, target_db, target_table, inputs[0],load_type)
  File "/opt/airflow/scripts/s3_db.py", line 253, in db_file_write
    input_df.write
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 1396, in save
    self._jwrite.save()
  File "/usr/local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/usr/local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 175, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Column flair	hour	day	month	year	title	num_comments	score	award_count not found in schema Some(StructType(StructField(flair,StringType,true),StructField(hour,IntegerType,true),StructField(day,IntegerType,true),StructField(month,IntegerType,true),StructField(year,IntegerType,true),StructField(title,IntegerType,true),StructField(num_comments,IntegerType,true),StructField(score,IntegerType,true),StructField(award_count,IntegerType,true))).
[2024-10-13T19:36:23.289+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_Demo, task_id=S3_to_DB, execution_date=20241013T193600, start_date=20241013T193616, end_date=20241013T193623
[2024-10-13T19:36:23.310+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 26 for task S3_to_DB (Column flair	hour	day	month	year	title	num_comments	score	award_count not found in schema Some(StructType(StructField(flair,StringType,true),StructField(hour,IntegerType,true),StructField(day,IntegerType,true),StructField(month,IntegerType,true),StructField(year,IntegerType,true),StructField(title,IntegerType,true),StructField(num_comments,IntegerType,true),StructField(score,IntegerType,true),StructField(award_count,IntegerType,true))).; 1247)
[2024-10-13T19:36:23.346+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-13T19:36:23.366+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
