[2024-10-13T22:25:54.065+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Demo.SFTP_to_S3 manual__2024-10-13T22:25:52.023065+00:00 [queued]>
[2024-10-13T22:25:54.068+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Demo.SFTP_to_S3 manual__2024-10-13T22:25:52.023065+00:00 [queued]>
[2024-10-13T22:25:54.068+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T22:25:54.069+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-13T22:25:54.069+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T22:25:54.073+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): SFTP_to_S3> on 2024-10-13 22:25:52.023065+00:00
[2024-10-13T22:25:54.076+0000] {standard_task_runner.py:55} INFO - Started process 215 to run task
[2024-10-13T22:25:54.078+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Demo', 'SFTP_to_S3', 'manual__2024-10-13T22:25:52.023065+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Demo.py', '--cfg-path', '/tmp/tmp38_r178v']
[2024-10-13T22:25:54.079+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask SFTP_to_S3
[2024-10-13T22:25:54.087+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T22:25:54.109+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Demo.SFTP_to_S3 manual__2024-10-13T22:25:52.023065+00:00 [running]> on host 764f93acab86
[2024-10-13T22:25:54.146+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Demo
AIRFLOW_CTX_TASK_ID=SFTP_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T22:25:52.023065+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T22:25:52.023065+00:00
[2024-10-13T22:25:54.148+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/sftp_s3.py", line 338, in main_sftp_s3
    s3_conn['s3_access_key'] = secret_vals[ts3_access]['s3_access_key']
KeyError: 'sd_s3_accesss'
[2024-10-13T22:25:54.152+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_Demo, task_id=SFTP_to_S3, execution_date=20241013T222552, start_date=20241013T222554, end_date=20241013T222554
[2024-10-13T22:25:54.156+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 34 for task SFTP_to_S3 ('sd_s3_accesss'; 215)
[2024-10-13T22:25:54.175+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-13T22:25:54.185+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
