[2024-10-13T21:07:37.327+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:07:35.163309+00:00 [queued]>
[2024-10-13T21:07:37.331+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:07:35.163309+00:00 [queued]>
[2024-10-13T21:07:37.331+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T21:07:37.331+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-13T21:07:37.331+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T21:07:37.336+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): SFTP_to_S3> on 2024-10-13 21:07:35.163309+00:00
[2024-10-13T21:07:37.341+0000] {standard_task_runner.py:55} INFO - Started process 312 to run task
[2024-10-13T21:07:37.343+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Test_2', 'SFTP_to_S3', 'manual__2024-10-13T21:07:35.163309+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Test_2.py', '--cfg-path', '/tmp/tmptcflw8b1']
[2024-10-13T21:07:37.344+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask SFTP_to_S3
[2024-10-13T21:07:37.352+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T21:07:37.374+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:07:35.163309+00:00 [running]> on host 764f93acab86
[2024-10-13T21:07:37.408+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Test_2
AIRFLOW_CTX_TASK_ID=SFTP_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T21:07:35.163309+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T21:07:35.163309+00:00
[2024-10-13T21:07:37.409+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/sftp_s3.py", line 328, in main_sftp_s3
    sftp_conn['host'] = secret_vals[ssftp_access]['host']
KeyError: 'sd_sftp_access'
[2024-10-13T21:07:37.414+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_Test_2, task_id=SFTP_to_S3, execution_date=20241013T210735, start_date=20241013T210737, end_date=20241013T210737
[2024-10-13T21:07:37.418+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task SFTP_to_S3 ('sd_sftp_access'; 312)
[2024-10-13T21:07:37.442+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-13T21:07:37.453+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
