[2024-10-13T19:50:43.314+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:45:16.260187+00:00 [queued]>
[2024-10-13T19:50:43.317+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:45:16.260187+00:00 [queued]>
[2024-10-13T19:50:43.317+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:50:43.318+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2024-10-13T19:50:43.318+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T19:50:43.322+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): S3_to_DB> on 2024-10-13 19:45:16.260187+00:00
[2024-10-13T19:50:43.325+0000] {standard_task_runner.py:55} INFO - Started process 1803 to run task
[2024-10-13T19:50:43.327+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Demo', 'S3_to_DB', 'manual__2024-10-13T19:45:16.260187+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Demo.py', '--cfg-path', '/tmp/tmp2h4k3t26']
[2024-10-13T19:50:43.328+0000] {standard_task_runner.py:83} INFO - Job 38: Subtask S3_to_DB
[2024-10-13T19:50:43.334+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T19:50:43.354+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Demo.S3_to_DB manual__2024-10-13T19:45:16.260187+00:00 [running]> on host c3a571b96d5f
[2024-10-13T19:50:43.388+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Demo
AIRFLOW_CTX_TASK_ID=S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T19:45:16.260187+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T19:45:16.260187+00:00
[2024-10-13T19:50:43.390+0000] {s3_db.py:129} INFO - Executing S3 File read.......
[2024-10-13T19:50:43.390+0000] {s3_db.py:16} INFO - Creating Spark session ......
[2024-10-13T19:50:46.069+0000] {s3_db.py:71} INFO - Executing File pattern check......
[2024-10-13T19:50:46.071+0000] {logging_mixin.py:137} INFO - prefix: sftp_file_receiver
[2024-10-13T19:50:46.595+0000] {s3_db.py:111} INFO - No files found at s3a://sdevalla-buck/sftp_file_receiver/sftp_s3_yyyymmdd.txt for input file pattern
[2024-10-13T19:50:46.597+0000] {s3_db.py:170} ERROR - No latest file found
[2024-10-13T19:50:46.606+0000] {s3_db.py:51} INFO - Updating run log for read operation....
[2024-10-13T19:50:46.608+0000] {s3_db.py:55} INFO - Run log updated successfully....
[2024-10-13T19:50:46.610+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/s3_db.py", line 312, in main_s3_db
    run_logger(dag_id, run_id ,'S3-DB',task_order,'insert',s3_access ,source_s3_path , f'{inputs[1]}' , 'write', f'{result}',db_access, target_table, '','success')
TypeError: 'NoneType' object is not subscriptable
[2024-10-13T19:50:46.631+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_Demo, task_id=S3_to_DB, execution_date=20241013T194516, start_date=20241013T195043, end_date=20241013T195046
[2024-10-13T19:50:46.647+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 38 for task S3_to_DB ('NoneType' object is not subscriptable; 1803)
[2024-10-13T19:50:46.694+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-13T19:50:46.745+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
