[2024-10-13T21:09:13.155+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:09:11.308042+00:00 [queued]>
[2024-10-13T21:09:13.159+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:09:11.308042+00:00 [queued]>
[2024-10-13T21:09:13.159+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T21:09:13.159+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-13T21:09:13.159+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-13T21:09:13.164+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): SFTP_to_S3> on 2024-10-13 21:09:11.308042+00:00
[2024-10-13T21:09:13.168+0000] {standard_task_runner.py:55} INFO - Started process 369 to run task
[2024-10-13T21:09:13.170+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_Test_2', 'SFTP_to_S3', 'manual__2024-10-13T21:09:11.308042+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_Test_2.py', '--cfg-path', '/tmp/tmp3bkaq76r']
[2024-10-13T21:09:13.171+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask SFTP_to_S3
[2024-10-13T21:09:13.178+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-13T21:09:13.203+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_Test_2.SFTP_to_S3 manual__2024-10-13T21:09:11.308042+00:00 [running]> on host 764f93acab86
[2024-10-13T21:09:13.259+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_Test_2
AIRFLOW_CTX_TASK_ID=SFTP_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-13T21:09:11.308042+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-13T21:09:11.308042+00:00
[2024-10-13T21:09:13.262+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/sftp_s3.py", line 332, in main_sftp_s3
    s3_conn['s3_access_key'] = secret_vals[ts3_access]['s3_access_key']
KeyError: 's3_access'
[2024-10-13T21:09:13.266+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_Test_2, task_id=SFTP_to_S3, execution_date=20241013T210911, start_date=20241013T210913, end_date=20241013T210913
[2024-10-13T21:09:13.271+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task SFTP_to_S3 ('s3_access'; 369)
[2024-10-13T21:09:13.310+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-13T21:09:13.321+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
